### ISSUE TITLE
pipeline gets triggered on PR close

### ISSUE THREAD

**Issue by goern** [thoth-station/aicoe-ci#2]
**Describe the bug**
A PipelineRun is triggered on closing a PR.

**Expected behavior**
the build pipeline should not be triggered

**Additional context**
Maybe some other pipeline can be triggered (later).

**Comment by harshad16** [comment]
This commit handles the issue: https://github.com/thoth-station/aicoe-ci/commit/64260896e9da8fff36844b231de6485bd366149d
and the issue doesn't occur anymore.
