### ISSUE TITLE
Show coala check in PR comments

### ISSUE THREAD

**Issue by pacospace** [thoth-station/aicoe-ci#24]
As User of Thoth CI,

I would like to see coala errrors as comment in the PR so that I can take actions faster.

**Comment by harshad16** [comment]
cool, will switch on the comment :+1:

**Comment by harshad16** [comment]
This commit would handle this issue: https://github.com/thoth-station/aicoe-ci/commit/81cc589a2eb1254c284644d66fc7af7f268e0bb8
